format = """\
  $username\
  $hostname\
  $localip\
  $shlvl\
  $directory\
  $vcsh\
  $fossil_branch\
  $fossil_metrics\
  $git_branch\
  $git_commit\
  $git_state\
  $git_metrics\
  $git_status\
  $hg_branch\
  $pijul_channel\
  ${custom.arc}\
  $docker_context\
  $lua\
  $nix_shell\
  $memory_usage\
  $direnv\
  $env_var\
  $custom\
  $sudo\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
  $time\
  $status\
  $os\
  $container\
  $shell\
  $character\
"""

[custom.arc]
shell = [ "fish", "-N" ]
ignore_timeout = true
when = """
command arc info | grep "^branch:" | string sub -s 9
test $status -eq 0
"""
command = """
command arc info | grep "^branch:" | string sub -s 9
"""
symbol = " "
format = "on [$symbol($output)]($style) "
