name: Automatically update flake inputs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: cachix/install-nix-action@v18
        env:
          NIX_VERSION: nix-2.5pre20211026_5667822
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/${{ env.NIX_VERSION }}/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Recreate and commit changes to the flake's lock file
        run: nix flake update --commit-lock-file .config
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4.2.1
        with:
          base: master
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: Update flake inputs
          branch: update/flake-inputs
          branch-suffix: short-commit-hash
          delete-branch: true
          assignees: IvanDyachenko
          reviewers: IvanDyachenko
