name: 'System build'
on:
  push:
    branches:
      - master
    paths:
      - '**.nix'
  pull_request:
    branches:
      - master
    paths:
      - '**.nix'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      # Installs Nix on GitHub Actions.
      - uses: cachix/install-nix-action@v23
        env:
          NIX_VERSION: nix-2.5pre20211026_5667822
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/${{ env.NIX_VERSION }}/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      # Build software only once and put it in a global cache.
      - uses: cachix/cachix-action@v11
        with:
          name: ivandyachenko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Run flake checks
        run: |
          nix flake check -v --show-trace .config
        timeout-minutes: 240
